---
- hosts: localhost

  tasks:
    - name: start container
      docker_container:
        name: test
        image: centos
        state: started
        exposed_ports:
          - 80
        ports: "81:81"
        tty: true
        detach: true
